<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resource\building.png" />
    <None Remove="Resource\hand.png" />
    <None Remove="Resource\hp.png" />
    <None Remove="Resource\inventory.png" />
    <None Remove="Resource\kaystanddown0.png" />
    <None Remove="Resource\kaystanddown1.png" />
    <None Remove="Resource\kaystandleft0.png" />
    <None Remove="Resource\kaystandright0.png" />
    <None Remove="Resource\kaystandup0.png" />
    <None Remove="Resource\kaystandup1.png" />
    <None Remove="Resource\kaywalkdown0.png" />
    <None Remove="Resource\kaywalkdown1.png" />
    <None Remove="Resource\kaywalkleft0.png" />
    <None Remove="Resource\kaywalkleft1.png" />
    <None Remove="Resource\kaywalkright0.png" />
    <None Remove="Resource\kaywalkright1.png" />
    <None Remove="Resource\kaywalkup0.png" />
    <None Remove="Resource\kaywallkup1.png" />
    <None Remove="Resource\mp.png" />
    <None Remove="Resource\stamina.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resource\building.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\hand.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\hp.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\inventory.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaystanddown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaystanddown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaystandleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaystandright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaystandup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaystandup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkleft1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkright1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywallkup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\mp.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\stamina.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
