<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resource\attack_down.png" />
    <None Remove="Resource\attack_left.png" />
    <None Remove="Resource\attack_right.png" />
    <None Remove="Resource\attack_up.png" />
    <None Remove="Resource\bossdeath.png" />
    <None Remove="Resource\building.png" />
    <None Remove="Resource\chatters0attackdown0.png" />
    <None Remove="Resource\chatters0attackdown1.png" />
    <None Remove="Resource\chatters0attackleft0.png" />
    <None Remove="Resource\chatters0attackleft1.png" />
    <None Remove="Resource\chatters0attackright0.png" />
    <None Remove="Resource\chatters0attackright1.png" />
    <None Remove="Resource\chatters0attackup0.png" />
    <None Remove="Resource\chatters0attackup1.png" />
    <None Remove="Resource\chatters0standdown0.png" />
    <None Remove="Resource\chatters0standdown1.png" />
    <None Remove="Resource\chatters0standleft0.png" />
    <None Remove="Resource\chatters0standright0.png" />
    <None Remove="Resource\chatters0standup0.png" />
    <None Remove="Resource\chatters0standup1.png" />
    <None Remove="Resource\chatters0walkdown0.png" />
    <None Remove="Resource\chatters0walkdown1.png" />
    <None Remove="Resource\chatters0walkleft0.png" />
    <None Remove="Resource\chatters0walkleft1.png" />
    <None Remove="Resource\chatters0walkright0.png" />
    <None Remove="Resource\chatters0walkright1.png" />
    <None Remove="Resource\chatters0walkup0.png" />
    <None Remove="Resource\chatters0wallkup1.png" />
    <None Remove="Resource\chatters_attack_down.png" />
    <None Remove="Resource\chatters_attack_left.png" />
    <None Remove="Resource\chatters_attack_right.png" />
    <None Remove="Resource\chatters_attack_up.png" />
    <None Remove="Resource\damage.png" />
    <None Remove="Resource\death.png" />
    <None Remove="Resource\find.png" />
    <None Remove="Resource\halalcartstanddown0.png" />
    <None Remove="Resource\hand.png" />
    <None Remove="Resource\heal_recovery.png" />
    <None Remove="Resource\hp.png" />
    <None Remove="Resource\inventory.png" />
    <None Remove="Resource\item1.png" />
    <None Remove="Resource\item10.png" />
    <None Remove="Resource\item11.png" />
    <None Remove="Resource\item12.png" />
    <None Remove="Resource\item13.png" />
    <None Remove="Resource\item14.png" />
    <None Remove="Resource\item15.png" />
    <None Remove="Resource\item16.png" />
    <None Remove="Resource\item17.png" />
    <None Remove="Resource\item18.png" />
    <None Remove="Resource\item19.png" />
    <None Remove="Resource\item2.png" />
    <None Remove="Resource\item3.png" />
    <None Remove="Resource\item4.png" />
    <None Remove="Resource\item5.png" />
    <None Remove="Resource\item6.png" />
    <None Remove="Resource\item7.png" />
    <None Remove="Resource\item8.png" />
    <None Remove="Resource\item9.png" />
    <None Remove="Resource\karaattackdown0.png" />
    <None Remove="Resource\karaattackdown1.png" />
    <None Remove="Resource\karaattackleft0.png" />
    <None Remove="Resource\karaattackleft1.png" />
    <None Remove="Resource\karaattackright0.png" />
    <None Remove="Resource\karaattackright1.png" />
    <None Remove="Resource\karaattackup0.png" />
    <None Remove="Resource\karaattackup1.png" />
    <None Remove="Resource\kararolldown0.png" />
    <None Remove="Resource\kararollleft0.png" />
    <None Remove="Resource\kararollright0.png" />
    <None Remove="Resource\kararollup0.png" />
    <None Remove="Resource\karastanddown0.png" />
    <None Remove="Resource\karastanddown1.png" />
    <None Remove="Resource\karastandleft0.png" />
    <None Remove="Resource\karastandright0.png" />
    <None Remove="Resource\karastandup0.png" />
    <None Remove="Resource\karastandup1.png" />
    <None Remove="Resource\karawalkdown0.png" />
    <None Remove="Resource\karawalkdown1.png" />
    <None Remove="Resource\karawalkleft0.png" />
    <None Remove="Resource\karawalkleft1.png" />
    <None Remove="Resource\karawalkright0.png" />
    <None Remove="Resource\karawalkright1.png" />
    <None Remove="Resource\karawalkup0.png" />
    <None Remove="Resource\karawelcomedown0.png" />
    <None Remove="Resource\karawelcomeleft0.png" />
    <None Remove="Resource\karawelcomeright0.png" />
    <None Remove="Resource\karawelcomeup0.png" />
    <None Remove="Resource\kayattackdown0.png" />
    <None Remove="Resource\kayattackright0.png" />
    <None Remove="Resource\kayattackright1.png" />
    <None Remove="Resource\kayattackup0.png" />
    <None Remove="Resource\kayattackup1.png" />
    <None Remove="Resource\kayrolldown0.png" />
    <None Remove="Resource\kayrollleft0.png" />
    <None Remove="Resource\kayrollright0.png" />
    <None Remove="Resource\kayrollup0.png" />
    <None Remove="Resource\kaystanddown0.png" />
    <None Remove="Resource\kaystanddown1.png" />
    <None Remove="Resource\kaystandleft0.png" />
    <None Remove="Resource\kaystandright0.png" />
    <None Remove="Resource\kaystandup0.png" />
    <None Remove="Resource\kaystandup1.png" />
    <None Remove="Resource\kaywalkdown0.png" />
    <None Remove="Resource\kaywalkdown1.png" />
    <None Remove="Resource\kaywalkleft0.png" />
    <None Remove="Resource\kaywalkleft1.png" />
    <None Remove="Resource\kaywalkright0.png" />
    <None Remove="Resource\kaywalkright1.png" />
    <None Remove="Resource\kaywalkup0.png" />
    <None Remove="Resource\kaywalkup1.png" />
    <None Remove="Resource\kaywallkup1.png" />
    <None Remove="Resource\kaywelcomedown0.png" />
    <None Remove="Resource\kaywelcomeleft0.png" />
    <None Remove="Resource\kaywelcomeright0.png" />
    <None Remove="Resource\kaywelcomeup0.png" />
    <None Remove="Resource\lancev0attackdown0.png" />
    <None Remove="Resource\lancev0attackdown1.png" />
    <None Remove="Resource\lancev0attackleft0.png" />
    <None Remove="Resource\lancev0attackleft1.png" />
    <None Remove="Resource\lancev0attackright0.png" />
    <None Remove="Resource\lancev0attackright1.png" />
    <None Remove="Resource\lancev0attackup0.png" />
    <None Remove="Resource\lancev0attackup1.png" />
    <None Remove="Resource\lancev0rolldown0.png" />
    <None Remove="Resource\lancev0rollleft0.png" />
    <None Remove="Resource\lancev0rollright0.png" />
    <None Remove="Resource\lancev0rollup0.png" />
    <None Remove="Resource\lancev0shootdown0.png" />
    <None Remove="Resource\lancev0shootleft0.png" />
    <None Remove="Resource\lancev0shootright0.png" />
    <None Remove="Resource\lancev0shootup0.png" />
    <None Remove="Resource\lancev0splashdown0.png" />
    <None Remove="Resource\lancev0splashdown1.png" />
    <None Remove="Resource\lancev0standdown0.png" />
    <None Remove="Resource\lancev0standleft0.png" />
    <None Remove="Resource\lancev0standright0.png" />
    <None Remove="Resource\lancev0standup0.png" />
    <None Remove="Resource\lancev0walkdown0.png" />
    <None Remove="Resource\lancev0walkdown1.png" />
    <None Remove="Resource\lancev0walkleft0.png" />
    <None Remove="Resource\lancev0walkleft1.png" />
    <None Remove="Resource\lancev0walkright0.png" />
    <None Remove="Resource\lancev0walkright1.png" />
    <None Remove="Resource\lancev0walkup0.png" />
    <None Remove="Resource\lancev0walkup1.png" />
    <None Remove="Resource\lancev1attackdown0.png" />
    <None Remove="Resource\lancev1attackdown1.png" />
    <None Remove="Resource\lancev1attackleft0.png" />
    <None Remove="Resource\lancev1attackleft1.png" />
    <None Remove="Resource\lancev1attackright0.png" />
    <None Remove="Resource\lancev1attackright1.png" />
    <None Remove="Resource\lancev1attackup0.png" />
    <None Remove="Resource\lancev1attackup1.png" />
    <None Remove="Resource\lancev1rolldown0.png" />
    <None Remove="Resource\lancev1rollleft0.png" />
    <None Remove="Resource\lancev1rollright0.png" />
    <None Remove="Resource\lancev1rollup0.png" />
    <None Remove="Resource\lancev1splashdown0.png" />
    <None Remove="Resource\lancev1splashdown1.png" />
    <None Remove="Resource\lancev1standdown0.png" />
    <None Remove="Resource\lancev1standleft0.png" />
    <None Remove="Resource\lancev1standright0.png" />
    <None Remove="Resource\lancev1standup0.png" />
    <None Remove="Resource\lancev1walkdown0.png" />
    <None Remove="Resource\lancev1walkdown1.png" />
    <None Remove="Resource\lancev1walkleft0.png" />
    <None Remove="Resource\lancev1walkleft1.png" />
    <None Remove="Resource\lancev1walkright0.png" />
    <None Remove="Resource\lancev1walkright1.png" />
    <None Remove="Resource\lancev1walkup0.png" />
    <None Remove="Resource\lancev1walkup1.png" />
    <None Remove="Resource\lancevshadow0.png" />
    <None Remove="Resource\lancevshadow1.png" />
    <None Remove="Resource\lancev_attack_down.png" />
    <None Remove="Resource\lancev_attack_left.png" />
    <None Remove="Resource\lancev_attack_right.png" />
    <None Remove="Resource\lancev_attack_up.png" />
    <None Remove="Resource\levelup.png" />
    <None Remove="Resource\mana_recovery.png" />
    <None Remove="Resource\mp.png" />
    <None Remove="Resource\music0.mp3" />
    <None Remove="Resource\music1.mp3" />
    <None Remove="Resource\music2.mp3" />
    <None Remove="Resource\newbie0standdown0.png" />
    <None Remove="Resource\newbie0standdown1.png" />
    <None Remove="Resource\newbie0standleft0.png" />
    <None Remove="Resource\newbie0standright0.png" />
    <None Remove="Resource\newbie0standup0.png" />
    <None Remove="Resource\newbie0standup1.png" />
    <None Remove="Resource\newbie0walkdown0.png" />
    <None Remove="Resource\newbie0walkdown1.png" />
    <None Remove="Resource\newbie0walkleft0.png" />
    <None Remove="Resource\newbie0walkleft1.png" />
    <None Remove="Resource\newbie0walkright0.png" />
    <None Remove="Resource\newbie0walkright1.png" />
    <None Remove="Resource\newbie0walkup0.png" />
    <None Remove="Resource\newbie0walkup1.png" />
    <None Remove="Resource\newbie1standdown0.png" />
    <None Remove="Resource\newbie1standdown1.png" />
    <None Remove="Resource\newbie1standleft0.png" />
    <None Remove="Resource\newbie1standright0.png" />
    <None Remove="Resource\newbie1standup0.png" />
    <None Remove="Resource\newbie1standup1.png" />
    <None Remove="Resource\newbie1walkdown0.png" />
    <None Remove="Resource\newbie1walkdown1.png" />
    <None Remove="Resource\newbie1walkleft0.png" />
    <None Remove="Resource\newbie1walkleft1.png" />
    <None Remove="Resource\newbie1walkright0.png" />
    <None Remove="Resource\newbie1walkright1.png" />
    <None Remove="Resource\newbie1walkup0.png" />
    <None Remove="Resource\newbie1walkup1.png" />
    <None Remove="Resource\saucer.png" />
    <None Remove="Resource\shawarmaHP.png" />
    <None Remove="Resource\shawarmaMP.png" />
    <None Remove="Resource\stamina.png" />
    <None Remove="Resource\stamina_recovery.png" />
    <None Remove="Resource\wallstanddown0.png" />
    <None Remove="Resource\zastavka.png" />
    <None Remove="settings" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resource\attack_down.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\attack_left.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\attack_right.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\attack_up.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\bossdeath.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\building.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0attackdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0attackdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0attackleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0attackleft1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0attackright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0attackright1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0attackup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0attackup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0standdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0standdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0standleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0standright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0standup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0standup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0walkdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0walkdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0walkleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0walkleft1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0walkright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0walkright1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0walkup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters0wallkup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters_attack_down.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters_attack_left.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters_attack_right.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\chatters_attack_up.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\damage.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\death.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\find.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\halalcartstanddown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\hand.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\heal_recovery.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\hp.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\inventory.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\item1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\item10.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\item11.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\item12.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\item13.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\item14.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\item15.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\item16.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\item17.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\item18.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\item19.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\item2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\item3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\item4.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\item5.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\item6.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\item7.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\item8.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\item9.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karaattackdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karaattackdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karaattackleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karaattackleft1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karaattackright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karaattackright1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karaattackup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karaattackup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kararolldown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kararollleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kararollright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kararollup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karastanddown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karastanddown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karastandleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karastandright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karastandup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karastandup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karawalkdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karawalkdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karawalkleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karawalkleft1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karawalkright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karawalkright1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karawalkup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karawalkup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karawelcomedown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karawelcomeleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karawelcomeright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karawelcomeup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kayattackdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kayattackleft1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kayattackdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kayattackleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kayattackright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kayattackright1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kayattackup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kayattackup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kayrolldown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kayrollleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kayrollright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kayrollup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaystanddown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaystanddown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaystandleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaystandright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaystandup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaystandup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkleft1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkright1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywelcomedown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywelcomeleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywelcomeright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywelcomeup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0attackdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0attackdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0attackleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0attackleft1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0attackright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0attackright1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0attackup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0attackup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0rolldown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0rollleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0rollright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0rollup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0shootdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0shootleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0shootright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0shootup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0splashdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0splashdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0standdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0standleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0standright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0standup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0walkdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0walkdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0walkleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0walkleft1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0walkright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0walkright1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0walkup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev0walkup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1attackdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1attackdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1attackleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1attackleft1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1attackright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1attackright1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1attackup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1attackup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1rolldown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1rollleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1rollright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1rollup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1splashdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1splashdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1standdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1standleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1standright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1standup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1walkdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1walkdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1walkleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1walkleft1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1walkright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1walkright1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1walkup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev1walkup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancevshadow0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancevshadow1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev_attack_down.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev_attack_left.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev_attack_right.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\lancev_attack_up.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\levelup.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\mana_recovery.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\mp.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\music0.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\music1.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\music2.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0standdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0standdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0standleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0standright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0standup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0standup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0walkdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0walkdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0walkleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0walkleft1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0walkright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0walkright1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0walkup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0walkup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1standdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1standdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1standleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1standright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1standup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1standup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1walkdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1walkdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1walkleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1walkleft1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1walkright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1walkright1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1walkup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1walkup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\item0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\shawarmaHP.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\shawarmaMP.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\stamina.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\stamina_recovery.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\wallstanddown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resource\saucer.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Resource Include="Resource\zastavka.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Content Include="settings">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
