<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resource\building.png" />
    <None Remove="Resource\halalcartstanddown0.png" />
    <None Remove="Resource\hand.png" />
    <None Remove="Resource\hp.png" />
    <None Remove="Resource\inventory.png" />
    <None Remove="Resource\karastanddown0.png" />
    <None Remove="Resource\karastanddown1.png" />
    <None Remove="Resource\karastandleft0.png" />
    <None Remove="Resource\karastandright0.png" />
    <None Remove="Resource\karastandup0.png" />
    <None Remove="Resource\karastandup1.png" />
    <None Remove="Resource\karawalkdown0.png" />
    <None Remove="Resource\karawalkdown1.png" />
    <None Remove="Resource\karawalkleft0.png" />
    <None Remove="Resource\karawalkleft1.png" />
    <None Remove="Resource\karawalkright0.png" />
    <None Remove="Resource\karawalkright1.png" />
    <None Remove="Resource\karawalkup0.png" />
    <None Remove="Resource\kaystanddown0.png" />
    <None Remove="Resource\kaystanddown1.png" />
    <None Remove="Resource\kaystandleft0.png" />
    <None Remove="Resource\kaystandright0.png" />
    <None Remove="Resource\kaystandup0.png" />
    <None Remove="Resource\kaystandup1.png" />
    <None Remove="Resource\kaywalkdown0.png" />
    <None Remove="Resource\kaywalkdown1.png" />
    <None Remove="Resource\kaywalkleft0.png" />
    <None Remove="Resource\kaywalkleft1.png" />
    <None Remove="Resource\kaywalkright0.png" />
    <None Remove="Resource\kaywalkright1.png" />
    <None Remove="Resource\kaywalkup0.png" />
    <None Remove="Resource\kaywalkup1.png" />
    <None Remove="Resource\kaywallkup1.png" />
    <None Remove="Resource\mp.png" />
    <None Remove="Resource\newbie0standdown0.png" />
    <None Remove="Resource\newbie0standdown1.png" />
    <None Remove="Resource\newbie0standleft0.png" />
    <None Remove="Resource\newbie0standright0.png" />
    <None Remove="Resource\newbie0standup0.png" />
    <None Remove="Resource\newbie0standup1.png" />
    <None Remove="Resource\newbie0walkdown0.png" />
    <None Remove="Resource\newbie0walkdown1.png" />
    <None Remove="Resource\newbie0walkleft0.png" />
    <None Remove="Resource\newbie0walkleft1.png" />
    <None Remove="Resource\newbie0walkright0.png" />
    <None Remove="Resource\newbie0walkright1.png" />
    <None Remove="Resource\newbie0walkup0.png" />
    <None Remove="Resource\newbie0walkup1.png" />
    <None Remove="Resource\newbie1standdown0.png" />
    <None Remove="Resource\newbie1standdown1.png" />
    <None Remove="Resource\newbie1standleft0.png" />
    <None Remove="Resource\newbie1standright0.png" />
    <None Remove="Resource\newbie1standup0.png" />
    <None Remove="Resource\newbie1standup1.png" />
    <None Remove="Resource\newbie1walkdown0.png" />
    <None Remove="Resource\newbie1walkdown1.png" />
    <None Remove="Resource\newbie1walkleft0.png" />
    <None Remove="Resource\newbie1walkleft1.png" />
    <None Remove="Resource\newbie1walkright0.png" />
    <None Remove="Resource\newbie1walkright1.png" />
    <None Remove="Resource\newbie1walkup0.png" />
    <None Remove="Resource\newbie1walkup1.png" />
    <None Remove="Resource\nintendo.png" />
    <None Remove="Resource\saucer.png" />
    <None Remove="Resource\shawarmaHP.png" />
    <None Remove="Resource\shawarmaMP.png" />
    <None Remove="Resource\stamina.png" />
    <None Remove="Resource\wallstanddown0.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resource\building.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\halalcartstanddown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\hand.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\hp.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\inventory.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karastanddown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karastanddown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karastandleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karastandright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karastandup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karastandup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karawalkdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karawalkdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karawalkleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karawalkleft1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karawalkright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karawalkright1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karawalkup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\karawalkup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaystanddown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaystanddown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaystandleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaystandright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaystandup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaystandup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkleft1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkright1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\kaywalkup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\mp.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0standdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0standdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0standleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0standright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0standup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0standup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0walkdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0walkdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0walkleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0walkleft1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0walkright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0walkright1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0walkup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie0walkup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1standdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1standdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1standleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1standright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1standup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1standup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1walkdown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1walkdown1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1walkleft0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1walkleft1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1walkright0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1walkright1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1walkup0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\newbie1walkup1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\nintendo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\shawarmaHP.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\shawarmaMP.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\stamina.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\wallstanddown0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resource\saucer.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
